spring.datasource.url=jdbc:mysql://localhost:3306/petshop
server.port=8084
spring.application.name=pet-service
spring.datasource.username=root
spring.datasource.password=newpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
